apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-validator
  namespace: devops-exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-api  # שונה כדי להתאים ל-Service
  template:
    metadata:
      labels:
        app: validator-api  # שונה כדי להתאים ל-Service
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: validator-api
        image: secure-validator-api:latest # ודאי שזה השם שבנית ב-Docker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: APP_SECRET
        volumeMounts:
        - name: log-storage
          mountPath: /app/logs
      volumes:
      - name: log-storage
        emptyDir: {}