apiVersion: v1
kind: Service
metadata:
  name: validator-service
  namespace: devops-exam
spec:
  type: LoadBalancer 
  selector:
    app: secure-validator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080