apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: validator-ingress
  namespace: devops-exam
spec:
  rules:
    - host: validator.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: validator-svc
                port:
                  number: 80

